### ISSUE TITLE
Upcoming deprecation of decorateTopicTitle API

### ISSUE THREAD

**Issue by tyb-talks** [VaperinaDEV/solved-topic-badge#3]
Hi @VaperinaDEV, I noticed that this theme component makes use of the decorateTopicTitle API which will be deprecated from Discourse 3.3 (https://github.com/discourse/discourse/pull/24429). This is due to the inherent instability of what that API is enabling - directly modifying ember-rendered HTML can cause errors in Ember's rendering pipeline and crash the app. In addition, if Ember decides to re-use an element when component arguments change, the decorators will not be re-run.

The good news is, we can still use plugin-outlets to achieve the same outcome as the decorateTopicTitle API. You can check out https://github.com/discourse/discourse-calendar/pull/474 for an example. The `above-topic-list-item` / `after-topic-list-item` plugin outlets are also good candidates for the typical use cases we've seen with this API.

**Comment by VaperinaDEV** [comment]
Hi @tyb-talks, Thanks for the heads up! I'll use other method instead decorateTopicTitle API. 👍
